_BASE_: "./mask_rcnn_R_50_FPN_3x.yaml"
DATASETS:
  TRAIN: ("balloon/train",)
  TEST: ("coco_2014_minival",)
DATALOADER:
  NUM_WORKERS: 2

MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 300
