_BASE_: "./faster_rcnn_R_50_C4.yaml"
DATASETS:
  TRAIN: ("SNF_TEST/train",)
  TEST: ("SNF_TEST/val",)
DATALOADER:
  NUM_WORKERS: 2
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  BASE_LR: 0.00025
  WARMUP_ITERS: 100


